version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1 # Use the AWS ECR orb in your configuration
  aws-ecs: circleci/aws-ecs@3.2.0 # Use the AWS ECS orb in your configuration

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          path: .
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          registry-id: registry_id
          repo: $demo-cluster-prod
          # tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
          family: '$demo-cluster-prod-service'
          cluster: '$demo-cluster-prod-cluster'
          # container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

# VS Code Extension Version: 1.5.1