---
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.0 #123
  # tfsec: mycodeself/tfsec@1.1.0
jobs:
  # scan-example:
  #   parameters:
  #   executor: tfsec/default
  #   steps:
  #     - checkout
  #     - tfsec/scan: 
  #         directory: ./infrastructure
  #         exclude-checks: 'aws-ec2-require-vpc-flow-logs-for-all-vpcs,aws-ec2-enable-at-rest-encryption,aws-ec2-enforce-http-token-imds,aws-ec2-no-public-egress-sgr,aws-ec2-no-public-ingress-sgr'


  terraform-init:
    executor: terraform/default
    steps:
      - checkout
      - run : pwd
      - terraform/init:
          path: ./infrastructure

          


  terraform-validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/validate:
          path: ./infrastructure


  terraform-plan:
    executor: terraform/default
    steps:
      - checkout
      - terraform/plan:
          path: ./infrastructure


  terraform-apply:
    executor: terraform/default
    steps:
      - checkout
      - terraform/apply:
          path: ./infrastructure







workflows:
  deploy_infrastructure:
    jobs:

    # - scan-example


    - terraform-init:
        context: 
          - terraform
        # requires:
        # - scan-example
      


    - terraform-validate:
        context: 
          - terraform
        requires:
        - terraform-init


    - terraform-plan:
        context: 
          - terraform
        requires:
        - terraform-validate


    - approve-plan:
        type: approval
        requires:
        - terraform-plan


    - terraform-apply:
        context: 
          - terraform
        requires:
        # - terraform-plan
        - approve-plan



    - approve-apply:
        type: approval
        requires:
        # - approve-plan
        - terraform-apply



















# VS Code Extension Version: 1.5.1