---
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.0 
  # tfsec: mycodeself/tfsec@1.1.0
jobs:
  # scan-example:
  #   parameters:
  #   executor: tfsec/default
  #   steps:
  #     - checkout
  #     - tfsec/scan: 
  #         directory: ./infrastructure
  #         exclude-checks: 'aws-ec2-require-vpc-flow-logs-for-all-vpcs,aws-ec2-enable-at-rest-encryption,aws-ec2-enforce-http-token-imds,aws-ec2-no-public-egress-sgr,aws-ec2-no-public-ingress-sgr'


  terraform-init:
    executor: terraform/default
    steps:
      - checkout
      - run : pwd
      - terraform/init:
          path: ./infrastructure

          


  terraform-validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/validate:
          path: ./infrastructure


  terraform-plan:
    executor: terraform/default
    steps:
      - checkout
      - terraform/plan:
          path: ./infrastructure


  terraform-apply:
    executor: terraform/default
    steps:
      - checkout
      - terraform/apply:
          path: ./infrastructure

  terraform-destroy:
    executor: terraform/default
    steps:
      - checkout
      - run: 
          path: /root/project/infrastructure
          command: terraform init 
      - run: 
          path: /root/project/infrastructure
          command: terraform destroy -auto-approve


  docker:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout

      - run: apt update 

      - run: apt install curl -y

      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

      - run: unzip awscliv2.zip

      - run: sudo ./aws/install

      - run: curl -fsSL https://get.docker.com -o get-docker.sh

      - run: sudo sh get-docker.sh

      - run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 653524450879.dkr.ecr.eu-central-1.amazonaws.com

      - run: docker build -t demo-prod .

      - run: docker tag demo-prod:latest 653524450879.dkr.ecr.eu-central-1.amazonaws.com/demo-prod:latest

      - run: docker push 653524450879.dkr.ecr.eu-central-1.amazonaws.com/demo-prod:latest

  





workflows:
  deploy_infrastructure:
    jobs:

    # - scan-example


    - terraform-init:
        context: 
          - terraform
        # requires:
        # - scan-example
      


    - terraform-validate:
        context: 
          - terraform
        requires:
        - terraform-init


    - terraform-plan:
        context: 
          - terraform
        requires:
        - terraform-validate


    - approve-plan:
        type: approval
        requires:
        - terraform-plan


    - terraform-apply:
        context: 
          - terraform
        requires:
        # - terraform-plan
        - approve-plan



    - approve-apply:
        type: approval
        requires:
        # - approve-plan
        - terraform-apply

    - docker:
        requires:
         - approve-apply
    
    - terraform-destroy:
        type: approval
        requires:
         - docker



















# VS Code Extension Version: 1.5.1